sonar.projectKey=EdouardPlantevin_back_resto
sonar.organization=edouardplantevin

# Info projet
sonar.projectName=back_resto
sonar.projectVersion=1.0

# Encodage
sonar.sourceEncoding=UTF-8

# --- CONFIGURATION BACKEND (JAVA) ---
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.test.inclusions=**/*.spec.ts,**/*Test.java

sonar.java.binaries=target/classes

# Rapport de couverture Jacoco
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

# Exclusions (fichiers qu'on ne veut pas analyser)
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/target/**